### ISSUE TITLE
[BLOG] Integrate missing articles.

### ISSUE THREAD

**Issue by white-gorilla** [ELS-RD/ai.lefebvre-sarrut#20]
**The most recent.**

- [x] [Get 2x Faster Transcriptions with OpenAI Whisper Large on Kernl](https://www.reddit.com/r/MachineLearning/comments/10xp54e/p_get_2x_faster_transcriptions_with_openai/)
- [x] [Are LLM relevant for legal topics? `in draft`](https://els1.sharepoint.com/:w:/t/RD/EbsyTjY1_WdBsxbpBZtv0HoB3yLSFSkvXiw81JTYj2j6Aw?e=hh5hbi)

**Old articles.**

[see sharepoint](https://els1.sharepoint.com/:f:/t/RD/EozwVwnNNK1BvnjTBTyZEYABPTLrfQ2_8_DDbExJALHdMA?e=pG8Dez)

- [x] Decrease HuggingFace Transformers training times by 2 or more with dynamic padding and uniform length batching
- [x] Optimizing Transformer model to perform GPU inference UNDER 1ms latency
- [x] Why we switched from Spacy to Flair to anonymize French case law

**Comment by Veronique-rd** [comment]
Ajouter l'article LLM version longue https://els1.sharepoint.com/:w:/t/RD/EbsyTjY1_WdBsxbpBZtv0HoB3yLSFSkvXiw81JTYj2j6Aw?e=hh5hbi
